services:
  mq:
    image: rabbitmq:3.13-management
    hostname: 'my-rabbit'
    ports:
      - "5672:5672"
      - "15672:15672"
    env_file:
      - .env
    volumes:
      - "./data:/var/lib/rabbitmq/mnesia/"
      # - ./mqDefinitions.json:/etc/rabbitmq/mqDefinitions.json

  # redis:
  #   image: redis:latest
  #   ports:
  #     - "6379:6379"
    # volumes:
    #   - "./data/cache:/data"
