services:
  mq:
    image: rabbitmq:3.13-management
    hostname: 'my-rabbit'
    ports:
      - "5672:5672"
      - "15672:15672"
    env_file:
      - .env
    volumes:
      - "./data/rabbitmq:/var/lib/rabbitmq/mnesia/"
      # - ./mqDefinitions.json:/etc/rabbitmq/mqDefinitions.json

  db:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - "./data/db:/var/lib/postgresql/data"

  adminer:
    image: adminer:latest
    restart: always
    ports:
      - 8081:8080